Fix: restatectl dump cluster renders status for all live nodes
restatedev/restate pull request #2065
Opened 2024-10-11 13:08 UTC by pcholakov

This change fixes a trivial issue in the dump cluster sub-command where it would only print the partition processor status for one node rather than all nodes scheduler to run a given partition.

The server-side change is purely a cosmetic refactoring replacing an early if/continue with a two-arm match.

Example from a local three-worker / 4 partitions cluster:

```
> restatectl dump cluster --cluster-controller unix:restate-data/metadata-node/node.sock

🔄️ ALIVE PARTITION PROCESSORS:
――――――――――――――――――――――――――――――
 P-ID  NODE  RUN MODE  REPLAY  APPLIED LSN  PERSISTED LSN  OBSERVED LEADER  # SKIPS  LAST REFRESH
 0     N2:8  Leader    Active  8            ??             N2:8 - e8        0        1 second and 283 ms ago
 0     N3:8  Follower  Active  0            ??             ?? - ??          0        1 second and 148 ms ago
 1     N2:8  Leader    Active  4            ??             N2:8 - e9        0        1 second and 201 ms ago
 1     N3:8  Follower  Active  5            ??             ?? - ??          0        1 second and 455 ms ago
 2     N2:8  Leader    Active  8            ??             N2:8 - e8        0        1 second and 789 ms ago
 2     N3:8  Follower  Active  0            ??             ?? - ??          0        1 second and 112 ms ago
 3     N2:8  Leader    Active  8            ??             N2:8 - e8        0        1 second and 340 ms ago
 3     N3:8  Follower  Active  0            ??             ?? - ??          0        1 second and 491 ms ago

☠️ DEAD NODES:
―――――――――――――
 NODE  LAST SEEN ALIVE
 N4    38 seconds and 439 ms ago
```

As a side note, I think it would be useful if a cluster-dump command also displayed all known metadata servers and logs; this doesn't currently do that. I propose that we rename the current `dump cluster` subcommand to `partitions list-processors` and build a separate, more elaborate cluster inspection utility.

2024-10-14 08:51 UTC, AhmedSoliman commented
Perhaps this can be `partitions status` instead of dump cluster-state then?

2024-10-14 15:12 UTC, AhmedSoliman requested changes
Marking as as "request changed" to get it back to your queue.

2024-10-15 11:27 UTC, pcholakov commented on tools/restatectl/src/commands/dump/mod.rs
> +pub enum Dump {}
I'll come back to this shortly.

2024-10-15 11:28 UTC, pcholakov commented
Updated as suggested!

2024-10-15 11:31 UTC, AhmedSoliman approved these changes
🚢

2024-10-15 12:03 UTC, merged